/*
 * This source file was generated by the Gradle 'init' task
 */
package librarymanagementsystem;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Library library=new Library();
        Scanner sc=new Scanner(System.in);

        while(true)
        {
            System.out.println("\n1.Add Book\n2.Register User\n3.Borrow Book\n4.Return Book\n5.Show Avaiable Books\n6.Show User's Books\n7.Exit");
            System.out.println("Choose: ");

            int choice=sc.nextInt();
            sc.nextLine();

            switch (choice) {
                case 1:
                    System.out.println("Title: ");
                    String title=sc.nextLine();

                    System.out.println("Author: ");
                    String author=sc.nextLine();

                    System.out.println("ISBN: ");
                    String isbn=sc.nextLine();

                    library.addBook(new Book(title, author, isbn));
                    break;
            case 2:
                System.out.println("User ID: ");
                String id=sc.nextLine();

                System.out.println("Name: ");
                String name=sc.nextLine();

                library.registerUser(new User(name, id));
                break;
            
            case 3:
                System.out.println("User ID: ");
                String buid=sc.nextLine();

                System.out.println("Book ISBN: ");
                String bisbn=sc.nextLine();

                library.borrowBook(buid, bisbn);
                break;
            
            case 4:
                System.out.println("User Id: ");
                String ruid=sc.nextLine();

                System.out.println("Book ISBN: ");
                String rsbin=sc.nextLine();

                library.returnBook(ruid, rsbin);
                break;
            
            case 5:
                library.showAvailableBooks();
                break;
            case 6:
                System.out.println("User Id: ");
                String sid=sc.nextLine();
                
                library.showUserBooks(sid);
                break;
            
            case 7:
                System.out.println("Thanks for comeing!! Exiting..");
                return;
            
            default:
                    System.out.println("Invalid choice!!");
                    break;
            }
        }
    }
}
